---
# Fundamental topic for simulation clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"

# Topic publishing joint states
- ros_topic_name: "/joint_states_no_effort"
  gz_topic_name: "/world/panda_world/model/panda/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Topic accpeting joint cmd in position
- ros_topic_name: "/joint1/cmd_pos"
  gz_topic_name: "/model/panda/joint/fp3_joint1/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint2/cmd_pos"
  gz_topic_name: "/model/panda/joint/fp3_joint2/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint3/cmd_pos"
  gz_topic_name: "/model/panda/joint/fp3_joint3/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint4/cmd_pos"
  gz_topic_name: "/model/panda/joint/fp3_joint4/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint5/cmd_pos"
  gz_topic_name: "/model/panda/joint/fp3_joint5/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint6/cmd_pos"
  gz_topic_name: "/model/panda/joint/fp3_joint6/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint7/cmd_pos"
  gz_topic_name: "/model/panda/joint/fp3_joint7/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Topic accpeting joint cmd in force
- ros_topic_name: "/joint1/cmd_force"
  gz_topic_name: "/model/panda/joint/fp3_joint1/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint2/cmd_force"
  gz_topic_name: "/model/panda/joint/fp3_joint2/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint3/cmd_force"
  gz_topic_name: "/model/panda/joint/fp3_joint3/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint4/cmd_force"
  gz_topic_name: "/model/panda/joint/fp3_joint4/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint5/cmd_force"
  gz_topic_name: "/model/panda/joint/fp3_joint5/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint6/cmd_force"
  gz_topic_name: "/model/panda/joint/fp3_joint6/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/joint7/cmd_force"
  gz_topic_name: "/model/panda/joint/fp3_joint7/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
